language: node_js
node_js:
- '7.1'
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
  - "$HOME/.gem"
before_install:
- npm install -g gulp
script:
- gulp test
- gulp
deploy:
  provider: npm
  email: me@brianneisler.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: DshSt7XbIfl5+cLKbwiFADPo9OMQpL7GNAREy7edIe6+xhD9iDOK1m6zHxpL+ystA8aK7X6K3KWNxM88SzVSB9hrd5/azvJa7W9K2uBM7qWOUqZv2Whc6wSSAhmSExPkn2YWF7BT57i5TX/a/NVauQOtddfR+lY8cq6fTQrLKZbf70UYMGlg6pvP1LitMwyMt31JNEIK9AwXuS95FWt+nP6rT3tvMfLp+l6Z7CNcKaklSFSiaUUyJ1Ww859CE1J39z5oSFthpCJoPVs20dj4MfM3BF518OeLU5wHU9xN/qDolx3nEUMDUO2kObgPA8XyeQ+jKEU3hyYgqKYHZRWiJ17yDG13y8AKYOkbA15W2SsIFdyv8KnwEgpnGIhoLFZO+pndpQL6JBM3xZbpCa0rG0kEtZ+HqdMPRJ7dOz/Jkw3fittW94VHcz/Pear+/gnfUxo2FXCTDpbayKsu3fZ6UOWnzk0gL7B6BTcW9WFAeD+YIxnEpGratkSGWEh3jehpauF/XeAzXt7LAeFOSPpiQkxPrX8eg2y/prmR1h2FJXSBjPy6MnsmK55nk4W+U822qVV2I1xnWAp2l7hFyJWLCvpo8EOr5YEwvdvwjb4mL1R3VEG+1hutcwAYwBjxDKP9rNIF85fe8Foc6blAFMGzRM4nrogaMBRGmjax+iORyp4=
